import '@radix-ui/themes/styles.css';
import './theme.config.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme, ThemePanel } from '@radix-ui/themes';
import './globals.css';
import Navbar from './Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <Theme appearance='light' accentColor='green'>
          <Navbar />
          <main className='p-5 text-zinc-900'>{children}</main>
          <ThemePanel />
        </Theme>
      </body>
    </html>
  );
}
